# Generated by Django 5.0.7 on 2024-07-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_add_column_and_task_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='columns',
            new_name='column',
        ),
    ]
